In [1]:
import pandas as pd
import numpy as np

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_2017"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [3]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [4]:
df

,Opening,Opening.1,Title,Director,Cast,Genre,Studio,Ref.
0,JAN,13.0,Haraamkhor,Shlok Sharma,"Nawazuddin Siddiqui, Shweta Tripathi","Comedy, Crime",Sikhya EntertainmentKhusro Films,[17][18]
1,JAN,13.0,Ok Jaanu,Shaad Ali,"Aditya Roy Kapur, Shraddha Kapoor","Romance, Drama","Madras Talkies, Dharma Productions",[19][20]
2,JAN,20.0,Coffee with D,Vishal Mishra,"Sunil Grover, Zakir Hussain","Comedy, Crime",Apex Entertainment,[21]
3,JAN,25.0,Kaabil,Sanjay Gupta,"Hrithik Roshan, Yami Gautam","Action, Thriller",Filmkraft Productions Pvt. Ltd,[22][23]
4,JAN,25.0,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiqui","Crime, Action","Red Chillies Entertainment, Excel Entertainment",[24][25]
...,...,...,...,...,...,...,...,...
120,DEC,8.0,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy,Excel Entertainment,[180][181]
121,DEC,8.0,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller,"Dream Machine, Koning Entertainment & Dream In...",[182]
122,DEC,8.0,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama,"Aman Film Production, Angel's Production, Bros...",[183]
123,DEC,15.0,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller,Sikhya Entertainment,[184]
124,DEC,22.0,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama,Yash Raj Films,[185]

In [5]:
df_2017 = df[['Title','Director','Cast','Genre']]

In [6]:
df_2017

,Title,Director,Cast,Genre
0,Haraamkhor,Shlok Sharma,"Nawazuddin Siddiqui, Shweta Tripathi","Comedy, Crime"
1,Ok Jaanu,Shaad Ali,"Aditya Roy Kapur, Shraddha Kapoor","Romance, Drama"
2,Coffee with D,Vishal Mishra,"Sunil Grover, Zakir Hussain","Comedy, Crime"
3,Kaabil,Sanjay Gupta,"Hrithik Roshan, Yami Gautam","Action, Thriller"
4,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiqui","Crime, Action"
...,...,...,...,...
120,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy
121,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller
122,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama
123,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller
124,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama

In [7]:
df_2017 = df_2017.rename(columns={'Title':'title'})
df_2017 = df_2017.rename(columns={'Director':'directors'})
df_2017 = df_2017.rename(columns={'Cast':'actors'})
df_2017 = df_2017.rename(columns={'Genre':'genre'})

In [8]:
df_2017

,title,directors,actors,genre
0,Haraamkhor,Shlok Sharma,"Nawazuddin Siddiqui, Shweta Tripathi","Comedy, Crime"
1,Ok Jaanu,Shaad Ali,"Aditya Roy Kapur, Shraddha Kapoor","Romance, Drama"
2,Coffee with D,Vishal Mishra,"Sunil Grover, Zakir Hussain","Comedy, Crime"
3,Kaabil,Sanjay Gupta,"Hrithik Roshan, Yami Gautam","Action, Thriller"
4,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiqui","Crime, Action"
...,...,...,...,...
120,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy
121,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller
122,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama
123,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller
124,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama

In [9]:
df_2017['directors'] = df_2017['directors'].replace(np.nan, 'unknown')
df_2017['actors'] = df_2017['actors'].replace(np.nan, 'unknown')
df_2017['genre'] = df_2017['genre'].replace(np.nan, 'unknown')

In [10]:
df_2017['title'] = df_2017['title'].str.lower()

In [12]:
df_2017['comb'] = df_2017['directors'] + ' ' + df_2017['actors'] + ' '+ df_2017['genre']

In [13]:
df_2017

,title,directors,actors,genre,comb
0,haraamkhor,Shlok Sharma,"Nawazuddin Siddiqui, Shweta Tripathi","Comedy, Crime","Shlok Sharma Nawazuddin Siddiqui, Shweta Tripa..."
1,ok jaanu,Shaad Ali,"Aditya Roy Kapur, Shraddha Kapoor","Romance, Drama","Shaad Ali Aditya Roy Kapur, Shraddha Kapoor Ro..."
2,coffee with d,Vishal Mishra,"Sunil Grover, Zakir Hussain","Comedy, Crime","Vishal Mishra Sunil Grover, Zakir Hussain Come..."
3,kaabil,Sanjay Gupta,"Hrithik Roshan, Yami Gautam","Action, Thriller","Sanjay Gupta Hrithik Roshan, Yami Gautam Actio..."
4,raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiqui","Crime, Action","Rahul Dholakia Shah Rukh Khan, Mahira Khan, Na..."
...,...,...,...,...,...
120,fukrey returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy,"Mrighdeep Singh Lamba Pulkit Samrat, Priya Ana..."
121,game over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller,"Paresh Vinodray Savani Rajesh Sharma, Yashpal ..."
122,sallu ki shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama,"Mohammad Israr Ansari Zeenat Aman, Kiran Kumar..."
123,monsoon shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller,"Amit Kumar Nawazuddin Siddiqui, Vijay Varma & ..."
124,tiger zinda hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama,Ali Abbas Zafar Salman Khan & Katrina Kaif Act...